#cloud-config
package_update: true

packages:
  - net-tools
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - ceph-common

ntp:
  enabled: true
  ntp_client: chrony
  # Use a single NTP server to avoid time drift between nodes
  servers:
    - 0.pool.ntp.org

runcmd:
  #  Install docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - sudo usermod -aG docker vagrant